apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig.yaml

# Add labels to all resources.
commonLabels:
  app: mogdb-operator

# Add namespace to all resources.
namespace: data-plane1

# Value of this field is prepended to the names of all resources
# e.g. a deployment named "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace field above.
namePrefix: mogdb-operator-

resources:
  - ../../bases/cm
  - ../../bases/secret
  - ../../bases/deployment
  - ../../bases/rbac/cluster

images:
  - name: controller
    newName: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-operator
    newTag: dev.009

patchesStrategicMerge:
  # Customize the global configuration of the operator.
  - patches/cm/configmap_global.yaml
  # Customize the rclone configuration of the operator.
  - patches/cm/configmap_rclone.yaml
  # Customize the container of the operator.
  - patches/deployment/deployment_container_operator.yaml

patchesJson6902:
  - target: { group: "", version: v1, kind: Deployment, name: manager }
    path: patches/deployment/deployment_container_operator_metrics.yaml
  - target: { group: "", version: v1, kind: Deployment, name: manager }
    path: patches/deployment/deployment_container_operator_singlenamespace.yaml
  - path: patches/rbac/manager_role.yaml
    target: {group: rbac.authorization.k8s.io, version: v1, kind: ClusterRole, name: manager-role}
  - path: patches/rbac/manager_role_binding.yaml
    target: {group: rbac.authorization.k8s.io, version: v1, kind: ClusterRoleBinding, name: manager-rolebinding}
  - path: patches/rbac/leader_election_role.yaml
    target: {group: rbac.authorization.k8s.io, version: v1, kind: ClusterRole, name: leader-election-role}
  - path: patches/rbac/leader_election_role_binding.yaml
    target: {group: rbac.authorization.k8s.io, version: v1, kind: ClusterRoleBinding, name: leader-election-rolebinding}

# the following config is for teaching kustomize how to do var substitution
vars:
  - name: SA_NAME
    objref:
      apiVersion: v1
      kind: ServiceAccount
      name: controller-manager
    fieldref:
      fieldpath: metadata.name
  - name: TOKEN_SECRET_NAME
    objref:
      name: token
      kind: Secret
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: IMAGE_PULL_SECRET_NAME
    objref:
      apiVersion: v1
      kind: Secret
      name: huawei-registry
    fieldref:
      fieldpath: metadata.name
  - name: NAMESPACE
    objref:
      name: manager
      kind: Deployment
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.namespace
