# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - mogdb.enmotech.io_multiclusters.yaml
  - mogdb.enmotech.io_kubeclientconfigs.yaml
# +kubebuilder:scaffold:crdkustomizeresource
